---
version: '3'

services:
  frontend:
    build: .
    image: frontend:latest
    ports:
      - 880:8080
    restart: always

networks:
  default:
    name: distributed_system_network
    external: true
