---
version: '3'

services:
  report_microservice:
    build: .
    image: report_microservice:latest
    volumes:
      - ../../data/results/:/results/
      - ../../data/report/:/report/
    restart: always


networks:
  default:
    name: distributed_system_network
    external: true

