---
version: '3'

services:
  api_microservice:
    build: .
    image: storage_microservice:latest
    volumes:
      - ../../data/raw/:/raw/
      - ../../data/report/:/report/
    ports:
      - 5000:5000
    restart: always


networks:
  default:
    name: distributed_system_network
    external: true

