---
version: '3'

services:
  api_microservice:
    build: .
    image: storage_microservice:latest
    volumes:
      - ../../data/raw/:/raw/
      - ../../data/report/:/report/
      - ../../data/results/:/results/
      - ../../data/archive/:/archive/
      - ../../data/archivematica-metadata/:/archivematica-metadata/
      - ../../data/input/:/input/
      - ../../data/cache/:/cache/
    ports:
      - 5000:5000
    restart: unless-stopped


networks:
  default:
    name: distributed_system_network
    external: true

