---
version: '3'

services:
  qpcr_automation_microservice:
    build: .
    image: qpcr_automation:latest
    volumes:
      - ../../data/results/:/results/
      - ../../data/report/:/report/
    restart: always


networks:
  default:
    name: distributed_system_network
    external: true

